// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuK9Nvg_doH3nxfJaIlUEmoLgWe_4l-1E',
    appId: '1:704316808356:web:2f827d753c91d69f31da31',
    messagingSenderId: '704316808356',
    projectId: 'fudon-60dbb',
    authDomain: 'fudon-60dbb.firebaseapp.com',
    storageBucket: 'fudon-60dbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaM4aCEswV06z1oyz3FvcZFkEcYp_a1rs',
    appId: '1:704316808356:android:b4aa45426c8f610f31da31',
    messagingSenderId: '704316808356',
    projectId: 'fudon-60dbb',
    storageBucket: 'fudon-60dbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBag5lMy1kf15p9JK1PSF7qAxp7wT84w9M',
    appId: '1:704316808356:ios:c764d7dacb98186831da31',
    messagingSenderId: '704316808356',
    projectId: 'fudon-60dbb',
    storageBucket: 'fudon-60dbb.appspot.com',
    iosBundleId: 'com.example.fudon',
  );
}
